name       : speech-dispatcher
version    : 0.10.1
release    : 13
source     :
    - https://github.com/brailcom/speechd/releases/download/0.10.1/speech-dispatcher-0.10.1.tar.gz : 098c9e56f3226b2d9b98ba23b154bfc54ad29cdd3f2bc3e5cbb9eb55e7775448
homepage   : https://freebsoft.org/speechd
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Common high-level interface to speech synthesis
description: |
    Speech Dispatcher Project provides a high-level device independent layer for access to speech synthesis through a simple, stable and well documented interface.
builddeps  :
    - pkgconfig(dotconf)
    - pkgconfig(espeak-ng)
    - pkgconfig(glib-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(libpulse-simple)
    - pkgconfig(ao)
    - pkgconfig(alsa)
    - pkgconfig(python3)
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/0002-Apply-default-configuration.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
