name       : speech-dispatcher
version    : 0.8.6
release    : 5
source     :
    - https://devel.freebsoft.org/pub/projects/speechd/speech-dispatcher-0.8.6.tar.gz : c233dc3757c1f0d3676480d1052d42d88d18d29ab0cb0c8b5ce8edc3e7386ff8
license    : GPL-2.0
component  : desktop.library
summary    : Speech Dispatcher Project
description: |
    Speech Dispatcher Project
builddeps  :
    - pkgconfig(dotconf)
    - pkgconfig(espeak-ng)
    - pkgconfig(glib-2.0)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(libpulse-simple)
    - pkgconfig(ao)
    - pkgconfig(alsa)
    - pkgconfig(python-3.5)
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/0002-Apply-default-configuration.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
