name       : speech-dispatcher
version    : 0.11.1
release    : 16
source     :
    - https://github.com/brailcom/speechd/releases/download/0.11.1/speech-dispatcher-0.11.1.tar.gz : d1da12ed3dac84f13799b6a2ec39ba2d3ca21a8493f44dc1855bd0ba96c2ddc6
homepage   : https://freebsoft.org/speechd
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Common high-level interface to speech synthesis
description: |
    Speech Dispatcher Project provides a high-level device independent layer for access to speech synthesis through a simple, stable and well documented interface.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ao)
    - pkgconfig(dotconf)
    - pkgconfig(espeak-ng)
    - pkgconfig(glib-2.0)
    - pkgconfig(libpulse-simple)
    - pkgconfig(python3)
    - pkgconfig(sndfile)
setup      : |
    %apply_patches
    %reconfigure --disable-static  --with-kali=no --with-baratinoo=no --with-ibmtts=no --with-voxin=no
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
