name       : speech-dispatcher
version    : 0.8.5
release    : 1
source     :
    - https://devel.freebsoft.org/pub/projects/speechd/speech-dispatcher-0.8.5.tar.gz : 2b4b786d4c7de7bd8f15cd4bf7a4dcf1d7eda039c550c3a435d14345a1ed54a2
license    : GPL-2.0
component  : desktop.library
summary    : Speech Dispatcher Project
description: |
    Speech Dispatcher Project
builddeps  :
    - pkgconfig(dotconf)
    - pkgconfig(glib-2.0)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(libpulse-simple)
    - pkgconfig(ao)
    - pkgconfig(alsa)
    - pkgconfig(python-3.5)
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
