name       : speech-dispatcher
version    : 0.10.2
release    : 14
source     :
    - https://github.com/brailcom/speechd/releases/download/0.10.2/speech-dispatcher-0.10.2.tar.gz : b06319f201e15e56c6296653af5bcfc300cb348e972d517df8b06eac77eae2dc
homepage   : https://freebsoft.org/speechd
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Common high-level interface to speech synthesis
description: |
    Speech Dispatcher Project provides a high-level device independent layer for access to speech synthesis through a simple, stable and well documented interface.
builddeps  :
    - pkgconfig(dotconf)
    - pkgconfig(espeak-ng)
    - pkgconfig(glib-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(libpulse-simple)
    - pkgconfig(ao)
    - pkgconfig(alsa)
    - pkgconfig(python3)
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
